platform :ios, '9.0'

def required_pods
    pod 'Google-Mobile-Ads-SDK', '7.36.0'
    pod 'OpenBidSDK', '1.0.0'
end

//test comment for ci - from f1 branch
target 'SampleApp' do
    required_pods
end

